services:
  postgres_server:
    image: 'postgis/postgis:16-3.4'
    container_name: ${DB_HOST}
    environment:
      PGDATA: /var/lib/postgresql/data/${DB_HOST}/
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_SCHEMA: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - postgress_data:/var/lib/postgresql/data/
    command: -p ${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 50

volumes:
  postgress_data:
